version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patpul-app
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - ./.env:/var/www/html/.env
      # PENTING: Mount folder storage jika butuh file gambar awet walaupun container dihapus
      - ./storage/app/public:/var/www/html/storage/app/public
      # Agar hasil git pull (public/build) langsung aktif tanpa rebuild image
      - ./public/build:/var/www/html/public/build
      # Mount folder app & routes agar perubahan backend langsung aktif
      - ./app:/var/www/html/app
      - ./routes:/var/www/html/routes
      - ./resources:/var/www/html/resources
    networks:
      - patpul_db_network

networks:
  patpul_db_network:
    external: true
    name: application_integration_default
